# Generated by Django 4.2.3 on 2023-10-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backends", "0006_storageproviderdb"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageproviderdb",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="storageproviderdb",
            name="storage_type",
            field=models.CharField(
                choices=[
                    ("dropbox", "Dropbox"),
                    ("mongodb", "MongoDB"),
                    ("local", "Local"),
                ],
                max_length=20,
            ),
        ),
    ]
