# Generated by Django 4.2.3 on 2023-10-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backends", "0007_storageproviderdb_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storageproviderdb",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
