repos:
-   repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'  # add version here
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
        args: ["--without-hashes", "-f",  "requirements.txt", "--with", "prod", "--without", "dev", "-o", "requirements.txt"]