site_name: Qlued
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.footer
    - toc.follow

nav:
- Home: index.md
- "Guides":
  - guides/gen_guide.md
  - guides/user_guide.md
  - guides/dev_guide.md
- "Tutorials":
  - Rydberg: notebooks/rydberg_api_showcase.ipynb
  - Fermions: notebooks/fermions_api_showcase.ipynb


plugins:
  - mkdocs-jupyter

repo_url: https://github.com/alqor-ug/qlued
edit_uri: edit/main/docs/

markdown_extensions:
  - toc
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg