site_name: Qlued
theme:
  name: material
  palette:
    scheme: default
    primary: red
    accent: deep purple
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.footer
    - toc.follow

nav:
- Home: index.md
- Notebook page: notebooks/rydberg_api_showcase.ipynb


plugins:
  - mkdocs-jupyter

repo_url: https://github.com/alqor-ug/qlued
edit_uri: edit/main/docs/
