site_name: Qlued
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.footer
    - toc.follow

  custom_dir: docs/overrides

nav:
  - Home: index.md
  - Contributing: contributing.md
  - "Guides":
      - guides/gen_guide.md
      - guides/user_guide.md
      - "Own instance": guides/local_installation.md
      - guides/oauth.md
  - "Tutorials for v2":
      - Rydberg: notebooks/rydberg_api_showcase_v2.ipynb
      - Fermions: notebooks/fermions_api_showcase_v2.ipynb
      - Qiskit-Cold-Atoms: notebooks/rydberg_qiskit_dynamics.ipynb

  - "Tutorials":
      - Rydberg: notebooks/rydberg_api_showcase_v1.ipynb
      - Fermions: notebooks/fermions_api_showcase.ipynb

plugins:
  - mkdocs-jupyter
  - mike

repo_url: https://github.com/alqor-ug/qlued
edit_uri: edit/main/docs/

markdown_extensions:
  - toc
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  version:
    provider: mike
    default: latest
